#REM: This is the Rust formatter, it handle the layout; structure, syntax-format and more...

max_width             = 80    #REM: Char Sequence length per line
hard_tabs             = false #REM: Is use tab? If not then use literal spaces
tab_spaces            = 2     #REM: Number of space for tab/spaces

brace_style           = "SameLineWhere"
imports_layout        = "Vertical"
newline_style         = "Auto"
fn_params_layout      = "Tall"
control_brace_style   = "AlwaysSameLine"
remove_nested_parens  = true

unstable_features     = true  #REM: Do we use nightly release features?
                              #REM: Such as; unstable linter, rust fmt and etc...