max_width             = 80
hard_tabs             = false
tab_spaces            = 2

unstable_features     = true
brace_style           = "SameLineWhere"
imports_layout        = "Vertical"
newline_style         = "Auto"
fn_params_layout      = "Tall"
control_brace_style   = "AlwaysSameLine"
remove_nested_parens  = true